name: release

on:
  release:
    types:
      - created

jobs:
  cancel:
    name: 'Cancel previous runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  check:
    name: 'Lint and test'
    runs-on: ubuntu-latest
    needs: cancel
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Read flutter version
        id: get-flutter-version
        run: echo "::set-output name=version::$(cat FLUTTER_VERSION)"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Check lints
        run: flutter analyze
      - name: Run tests
        run: flutter test --concurrency=4

  deploy-web:
    name: 'Deploy web app'
    runs-on: ubuntu-latest
    needs: check
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Read flutter version
        id: get-flutter-version
        run: echo "::set-output name=version::$(cat FLUTTER_VERSION)"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build web
        run: flutter build web --release
      - name: Deploy to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: build/web
          bucket: staging.lura.so
          dist-id: ${{ secrets.CLOUDFRONT_DIST_ID }}
          bucket-region: eu-central-1
          no-cache: true
          delete-removed: true
